---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebanda-dev-test-nestjs-service-dev-build
  namespace: ebanda-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/erica-banda-03/ebanda-dev-test-nestjs-service-gitops.git
    targetRevision: HEAD
    path: ./helm/build
  destination:
    server: https://kubernetes.default.svc
    namespace: ebanda-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy      
